models: add missing required on_delete
Fixes the following error

    TypeError: __init__() missing 1 required positional argument: 'on_delete'

Signed-off-by: Alexander Alemayhu <alexander@alemayhu.com>